import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";

const localFont = LocalFont({
  src: "../public/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${localFont.className} antialiased mx-16`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
